parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\BudgetStateProvider:
        arguments:
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'

    App\State\RecurringEventDeleteProcessor:
        bind:
            $innerProcessor: '@api_platform.doctrine.orm.state.remove_processor'

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - name: kernel.event_listener
              event: lexik_jwt_authentication.on_authentication_success
              method: onAuthenticationSuccess
