parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\State\BudgetStateProvider:
        arguments:
            $itemProvider: '@api_platform.doctrine.orm.state.item_provider'
            $collectionProvider: '@api_platform.doctrine.orm.state.collection_provider'
