<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260429000004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Rename custom user FK indexes to Doctrine standard names; fix user table column defaults';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER INDEX idx_budget_user RENAME TO IDX_73F2F77BA76ED395');
        $this->addSql('ALTER INDEX idx_recurring_event_user RENAME TO IDX_51B1C7F8A76ED395');
        $this->addSql('ALTER INDEX idx_planned_item_user RENAME TO IDX_A4434883A76ED395');
        $this->addSql('ALTER INDEX idx_account_user RENAME TO IDX_7D3656A4A76ED395');
        $this->addSql('ALTER INDEX idx_transaction_user RENAME TO IDX_723705D1A76ED395');
        $this->addSql('ALTER INDEX idx_category_user RENAME TO IDX_64C19C1A76ED395');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER currency DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER INDEX IDX_73F2F77BA76ED395 RENAME TO idx_budget_user');
        $this->addSql('ALTER INDEX IDX_51B1C7F8A76ED395 RENAME TO idx_recurring_event_user');
        $this->addSql('ALTER INDEX IDX_A4434883A76ED395 RENAME TO idx_planned_item_user');
        $this->addSql('ALTER INDEX IDX_7D3656A4A76ED395 RENAME TO idx_account_user');
        $this->addSql('ALTER INDEX IDX_723705D1A76ED395 RENAME TO idx_transaction_user');
        $this->addSql('ALTER INDEX IDX_64C19C1A76ED395 RENAME TO idx_category_user');
    }
}
